application: cuppagefyp
version: 1 
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /
  script: staticpages.app

- url: /about
  script: staticpages.app

- url: /updates
  script: staticpages.app

- url: /projects
  script: main.app
  login: required
  auth_fail_action: redirect

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

